<link rel="stylesheet" type="text/css" href="vendor/twbs/bootstrap/dist/css/bootstrap.min.css"/>
<link rel="stylesheet" type="text/css" href="vendor/components/font-awesome/css/fontawesome.min.css"/>
<link rel="stylesheet" type="text/css" href="vendor/components/font-awesome/css/brands.min.css"/>
<link rel="stylesheet" type="text/css" href="vendor/components/font-awesome/css/regular.min.css"/>
<link rel="stylesheet" type="text/css" href="vendor/components/font-awesome/css/solid.min.css"/>
<link rel="stylesheet" type="text/css" href="css/diresa_principal.css"/>
<link rel="stylesheet" type="text/css" href="css/dataTable.css"/>
<link rel="stylesheet" type="text/css" href="css/responsive.css"/>
<link rel="stylesheet" type="text/css" href="datatable/DataTables-1.10.21/css/dataTables.bootstrap4.min.css"/>
<link rel="stylesheet" type="text/css" href="datatable/Buttons-1.6.2/css/buttons.dataTables.min.css"/>
<link rel="stylesheet" type="text/css" href="datatable/FixedColumns-3.3.1/css/fixedColumns.dataTables.min.css"/>
<link rel="stylesheet" type="text/css" href="datatable/Responsive-2.2.5/css/responsive.bootstrap4.min.css"/>
<link rel="stylesheet" type="text/css" href="datatable/DataTables-1.10.21/css/jquery.dataTables.min.css"/>
<link rel="stylesheet" type="text/css" href="vendor/OwlCarousel2/dist/assets/owl.carousel.min.css"/>
<link rel="stylesheet" type="text/css" href="vendor/OwlCarousel2/dist/assets/owl.theme.default.min.css"/>
<link rel="stylesheet" type="text/css" href="node_modules/js-year-calendar/dist/js-year-calendar.css"/>